### ISSUE TITLE
Issue running lightning

### ISSUE THREAD

**Issue by shaman-narayanasamy** [curoverse/lightning#2]
Dear authors,

I managed to install lightning using the docker container. I am able to open the container interactively, but I cannot pass the following step:

`
root@ad5ad1e58312:/home/lightning/lightning/experimental/pylightweb/lightning# python manage.py migrate
`

Below is the error I receive: 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 183, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 130, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "lightning"
```

Looking forward to hear from you.

Best regards,
Shaman

**Comment by shaman-narayanasamy** [comment]
Hi,

Seems like the issue was fixed. I think `postgress` did not install properly.

However, now the test is failing for me within the docker container.

`root@7e56095f480c:/home/lightning/lightning/experimental/pylightweb/lightning# python manage.py test tile_library`

```
Creating test database for alias 'default'...
.............................................................................................................s.......s...............................................................................................................F...
======================================================================
FAIL: test_failure_bad_response (tile_library.tests.TestLanternTranslatorModelOtherDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lightning/lightning/experimental/pylightweb/lightning/tile_library/tests.py", line 2009, in test_failure_bad_response
    self.assertIn('tile_library_int-tile_library_host', cm.exception.message_dict)
AssertionError: 'tile_library_int-tile_library_host' not found in {'tile_library_host': [u"HTTPConnectionPool(host='lightning-dev3.curoverse.com', port=80): Read timed out. (read timeout=1)"]}

----------------------------------------------------------------------
Ran 233 tests in 36.766s

FAILED (failures=1, skipped=2)
Destroying test database for alias 'default'...
```

Looking forward to your reply.

Best regards,
Shaman
